Dicom 4 error handling
NikolaiKovalenko/healthcare-dicom-dicomweb-adapter pull request #12
Opened 2020-07-22 12:59 UTC by NikolaiKovalenko

2020-07-22 13:00 UTC, NikolaiKovalenko commented on import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/CStoreService.java
> +      throw serviceException;
Do we need throw ex, or just set event

2020-07-22 16:47 UTC, oleksii-opanasenko requested changes

2020-07-22 16:47 UTC, oleksii-opanasenko commented on import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/CStoreService.java
> +        MonitoringService.addEvent(Event.CSTORE_BACKUP_ERROR);
We don`t need send event here. By contract - we sent events only when something finally failed. Not per every  resent attempt.

2020-07-22 16:47 UTC, oleksii-opanasenko commented on import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/CStoreService.java
> +        log.error("C-STORE request failed. Trying to resend...", e);
Please change log message to something like this: "Backup io processing during C-STORE request is failed."

2020-07-23 07:37 UTC, oleksii-opanasenko commented
LGTM

2020-07-23 07:37 UTC, merged